### ISSUE TITLE
Firefox 89+ / Proton compatibility - NoiaButtons v2.0.0+

### ISSUE THREAD

**Issue by Aris-t2** [Aris-t2/NoiaButtons#3]
Report all issues with new version here.

**Comment by Underx01** [comment]
@Aris-t2

Regarding to the issue I posted on CustomCSSforFx#308 closed-thread and as requested to continue in this thread (NoiaButtons v2.0.0#3) I write this post with all the things I tried to narrow the cause of the problem down:

**The issue explained:**
![Nav-icon issue](https://user-images.githubusercontent.com/22816976/120828293-a6bd0280-c55c-11eb-9431-5cd3689f1d6c.gif)
This issue starts after 4minutes (timed it) after opening/running Firefox 89+. So after 4minutes the icons start disappearing if I hover over them one by one (as seen in the Gif-file) or they completely disappear if I'm browsing (not hovering over the icons)

**What I tried (unfortunately without a solution):**
- A new/fresh Firefox profile without any add-ons/presonal prefs/used only NoiaButtons files without any files from CustomCSSforFX
- Tried Portable Firefox 89 (as suggested) with a new/fresh profile also without any add-ons/presonal prefs/used only NoiaButtons files without any files from CustomCSSforFX
- Turned off & turned on Proton, didn't matter
- Tried the same thing as above on a two different laptops, same exact issue
- Tried all different looks (1by1), didn't matter aswell (they also disappear after 4minutes):
```
/* @import "./css/toolbar_buttons_noia.css"; /**/
/* @import "./css/toolbar_buttons_firefox1.css"; /**/
/* @import "./css/toolbar_buttons_firefox2.css"; /**/
/* @import "./css/toolbar_buttons_firefox3.css"; /**/
/* @import "./css/toolbar_buttons_firefox3aero.css"; /**/
```
After trying all these things things to narrow the cause of the problem down, I think the problem lies either in this .css file:
`toolbar_buttons_base.css`
or there is something inside Firefox 89+ that's causing something to refresh/cache every 4minutes.

Hope this was a bit helpful and if there is a solution for it, that would be much appreciated.
Thanks in advance for your time reading this.

**Comment by Aris-t2** [comment]
Could you keep your toolbar configuration unchanged?

I tested default browser config + NoiaButtons on Fx 89 and 91 using new browser profiles, but this issue never occurred. Tested even 10-90 minutes on different machines.

**Comment by Underx01** [comment]
> 
> 
> Could you keep your toolbar configuration unchanged?
> 
> I tested default browser config + NoiaButtons on Fx 89 and 91 using new browser profiles, but this issue never occurred. Tested even 10-90 minutes on different machines.

Thank you for the quick reply. I found that the problem **only occurs with the 32bit version** of Firefox 89 (which I mainly use cause its way faster then the 64bit) and I think you were using the 64bit version and thats why the problem didn't occur.

I also tried the following as you suggested (with the 32bit version) without any results: 
- just left the default active settings that comes with NoiaButtons 2.0.0 + "about:config > toolkit.legacyUserProfileCustomizations.stylesheets > true" to activate it (didn't change any other settings, not even disabeling Proton)
- also left the toolbar/icons untouched and kept the default browser configs/without any customization in the toolbar 
(default icons + their positions)
- deleted all the content inside "Mozilla" folder inside C:\Users\MyPC\AppData\Local\Mozilla

I attached the 32bit profile if you want to test it yourself:
[Mozilla 32bit Profile.zip](https://github.com/Aris-t2/NoiaButtons/files/6604357/Mozilla.32bit.Profile.zip)

So far the 64bit Firefox 89 version works fine with all my active settings (NoiaButtons + latest CustomCSSforFX with Proton disabled) on all different laptops. I hope this was somewhat helpful and hope that you can find a solution for this odd issue that only occurs with the 32bit version of Firefox 89+

Thank you again in advance for looking into this.

**Comment by Underx01** [comment]
@Aris-t2 
Did you find any fix(es) for the 32bit issue I posted above?

Thanks in advance for your time looking into that.

**Comment by Aris-t2** [comment]
Unfortunately not. Application architecture has no effect on applying CSS code, at least there is no way to distinguish between 32 and 64Bit inside CSS files.

Also I could not reproduce the issue on a 32 Bit (Portable) Firefox on my system.

**Comment by pro100Hub** [comment]
@Aris-t2 
Hello. Detected a strange behavior with active tabs at the beginning and at the end of the navigation. When you hover on them, some area of text from the tab disappears.
Can you reproduce this problem in yourself? ↓
![9eYUG9ASvi](https://user-images.githubusercontent.com/10475278/126029921-574a0736-82b1-4452-b15c-ec31cc7c3a5e.gif)

**Comment by Aris-t2** [comment]
I can not reproduce this issue. Does this happen on a clean new profile too?

**Comment by pro100Hub** [comment]
> I can not reproduce this issue. Does this happen on a clean new profile too?

No, I did not try on another profile, but it seems this problem no longer appears on FF 91.

@Aris-t2, help please solve the problem: how to apply the style for the navigation arrows on the tab panel FF 91.  This class does not respond to changes to userChrome.css ↓
`#tabbrowser-arrowscrollbox:not([scrolledtostart])::part(overflow-start-indicator)`

For example, it is impossible to change the simple function `border-left: .5px solid rgba(255,255,255,.2)` on `border-left: .5px solid gray`
The fact is that the developers killed .css class `overflow-start-indicator`. `chrome: //browser/skin/tabbrowser/tab-overflow-indicator.png)` there is no longer anymore in FF 91. On the navigation buttons, there is no longer a shadow for separating the boundaries between the button and the tab :worried:

![firefox_QXCTs2X4mw](https://user-images.githubusercontent.com/10475278/129066278-7c150bac-8308-4996-8c9a-bc4497dc8288.jpg)

**Comment by Aris-t2** [comment]
You can't apply a style on tab navigation arrows. It is not possible anymore, even it default CSS inside Firefox code does exactly that.

The problem is the level CSS is registered on. userChrome.css and userContent.css are registered on a lower level, than required in this case.

A workaround would be custom JS scripts. There actually is one exactly for this case: https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/css_loader_author.uc.js

You have to setup CustomJSforFx method 2 first: https://github.com/Aris-t2/CustomJSforFx

**Comment by pro100Hub** [comment]
> A workaround would be custom JS scripts. There actually is one exactly for this case: https://github.com/Aris-t2/CustomJSforFx/blob/master/scripts/css_loader_author.uc.js

It works. Thank you very much, you are a wizard! :heartpulse:

@Aris-t2, one more question: is possible to remove the first separator in the drop-down search results list in FF 91?

![firefox_9GiwOBPo8h](https://user-images.githubusercontent.com/10475278/129070008-213fd289-6031-42e8-8e35-1189e3785e20.jpg)

**Comment by Aris-t2** [comment]
This should do the trick.

```css
.searchbar-separator {
   display: none !important;
}
```

**Comment by pro100Hub** [comment]
Thank you, i know this trick, but it cleans all the separators in the search results, there are two pieces there (from above and below as visible in the screenshot). I thought that can delete only the top, but the bottom separator leave.

**Comment by Aris-t2** [comment]
This is possible. Try:

```css
 .search-panel-header + .searchbar-separator {
   display: none !important;
}
```
